# Site settings
title: Zhaoyi Zhang
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhaoyi3264.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhaoyi Zhang
user_title: Undergrad @UW - Madison

email: zzhang825@wisc.edu
instagram: zhaoyi3264
facebook: 100013948779176
linkedin: zhang-zhaoyi
github: zhaoyi3264

# Bio
bio: I am an undergraduate student at UW - Madison and an undergraduate researcher at <a href="https://solislemuslab.github.io/" target="_blank" title="Lab website">Solis-Lemus Lab</a>. My research projects mainly foucs on the applicaiton of machine learning methods to DNA sequences. In my spare time, I enjoy <strong>programming, lifting weights, and <a href="https://www.worldcubeassociation.org/persons/2017ZHAN15" target="_blank" title="My official WCA records">solving Rubik&apos;s cubes</a></strong>.

# Education
education: I always feel like the more I learn, the less I know. While maintaining a good GPA at UW - Madison, I also take  courses on learning platforms or open courses from other universities to explore the infinite possibilities of computer programming.

# Expertise
expertise: I have developed a wide range of skills in data science, machine learning, and software development. Machine learning is so far my favorite subject. Recently, I am learning RNNs and experimenting with different architectures such as <a href="https://colab.research.google.com/drive/1v74eDwOqQZ0rEVDwroEGWngMjU2er6U_?usp=sharing" target="_blank" title="A Colab notebook">Char-RNN</a>.

ds: I feel comfortable working with various kinds of data using Pandas, Matplotlib, Seaborn, Tensorflow, scikit-learn, MySQL and more.
programming: My main development languages are Python and Java, but I am also familiar with JavaScript, C, MATLAB.
tools: Tools that I mostly use are Git, Linux, Docker, and Jupyter. In addition, I am learning and AWS.

# Projects
project: Here is a partial list of projects I built for classes, competitions, but mostly on my own time.

collections:
  projects:

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
