# Site settings
title: Zhaoyi Zhang
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zhaoyi3264.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Zhaoyi Zhang
user_title: Undergrad @UW - Madison

email: zzhang825@wisc.edu
instagram: zhaoyi3264
facebook: 100013948779176
linkedin: zhang-zhaoyi
github: zhaoyi3264

# Bio
bio: |
  I am a senior studying computer science, data science, and mathematics at the University of Wisconsin - Madison. I became interested in programming and computer science when I first learned how to program a LEGO robot in high school. Now, at the university, this passion remains with me. During my junior year, I developed a strong interest in backend engineering, which motivates me to learn major backend frameworks in three programming languages (Java, Python, and Node.js) and other popular technologies. I am sure these skills can help me succeed after entering the software development industry.
# In my spare time, I enjoy <strong>programming, lifting weights, and <a href="https://www.worldcubeassociation.org/persons/2017ZHAN15" target="_blank" title="My official WCA records">solving Rubik&apos;s cubes</a></strong>.

# Education
education: I always feel like the more I learn, the less I know. While maintaining a good GPA at UW - Madison, I also take  courses on learning platforms or open courses from other universities to explore the infinite possibilities of computer programming.

# Expertise
expertise: I have developed a wide range of skills in software development throughout my university education and internships.

programming: My main development languages are Java and Python, but I am also familiar with Node.js, C, MATLAB, and R.
frameworks: I am comfortable working with various kinds backend frameworks such as Spring, Hibernate, Flask, Express.js. At the same time, I also know a few frontend frameworks such as Thymeleaf,‌ ‌Jinja,‌ ‌Bootstrap,‌ ‌React.js‌ so that I can build simple websites.
tools: I have a lot of experience with MySQL, and some exposure to MongoDB. Developer tools that I use frequently are Git, Linux, Insomnia,‌ ‌Maven‌, and Docker. In addition, I am currently learning AWS.

# Projects
project: Here is a list of projects I built for classes, competitions, but mostly on my own time.

collections:
  projects:

# Google-analytics
google-analytics:
  id: "UA-203689793-1"

exclude: ['package.json', 'src' , 'node_modules']
